export const usersData = [
  { first_name: "Robert", last_name: "Sanders", tags: ["team","summit", "GITEX DUBAI"], email: "robert.sanders@example.com", profile_picture: "https://randomuser.me/api/portraits/men/11.jpg", date: "Friday, Jan 30 - 2026" },
  { first_name: "David", last_name: "Lee", tags: ["summit", "team", "GITEX DUBAI"], email: "david.lee@example.com", profile_picture: "https://randomuser.me/api/portraits/men/27.jpg", date: "Wednesday, Oct 15 - 2024" },
  { first_name: "James", last_name: "Brown", tags: [], email: "james.brown@example.com", profile_picture: "https://randomuser.me/api/portraits/men/44.jpg", date: "Tuesday, Feb 18 - 2025" },
  { first_name: "Olivia", last_name: "Garcia", tags: ["team", "summit"], email: "olivia.garcia@example.com", profile_picture: null, date: "Thursday, Jul 17 - 2025" },
  { first_name: "Ava", last_name: "Anderson", tags: [], email: "ava.anderson@example.com", profile_picture: null, date: "Monday, May 05 - 2025" },
  { first_name: "Sophia", last_name: "Martinez", tags: ["GITEX DUBAI","summit"], email: "sophia.martinez@example.com", profile_picture: null, date: "Sunday, Aug 24 - 2025" },
  { first_name: "William", last_name: "Taylor", tags: ["team", "summit"], email: "william.taylor@example.com", profile_picture: "https://randomuser.me/api/portraits/men/33.jpg", date: "Wednesday, Dec 11 - 2024" },
  { first_name: "Isabella", last_name: "Thomas", tags: ["summit", "GITEX DUBAI","team"], email: "isabella.thomas@example.com", profile_picture: null, date: "Friday, Sep 19 - 2025" },
  { first_name: "Henry", last_name: "Moore", tags: ["summit"], email: "henry.moore@example.com", profile_picture: "https://randomuser.me/api/portraits/men/45.jpg", date: "Tuesday, Aug 05 - 2025" },
  { first_name: "Emily", last_name: "Johnson", tags: [], email: "emily.johnson@example.com", profile_picture: null, date: "Monday, Mar 10 - 2025" },
  { first_name: "Mia", last_name: "Jackson", tags: [], email: "mia.jackson@example.com", profile_picture: null, date: "Thursday, Jun 26 - 2025" },
  { first_name: "Charlotte", last_name: "White", tags: [], email: "charlotte.white@example.com", profile_picture: null, date: "Sunday, Apr 20 - 2025" },
  { first_name: "Michael", last_name: "Wilson", tags: ["GITEX DUBAI"], email: "michael.wilson@example.com", profile_picture: "https://randomuser.me/api/portraits/men/62.jpg", date: "Saturday, Apr 12 - 2025" },
  { first_name: "Daniel", last_name: "Harris", tags: ["GITEX DUBAI", "team", "summit"], email: "daniel.harris@example.com", profile_picture: "https://randomuser.me/api/portraits/men/12.jpg", date: "Monday, Feb 09 - 2026" },
  { first_name: "Amelia", last_name: "Clark", tags: ["team", "GITEX DUBAI"], email: "amelia.clark@example.com", profile_picture: null, date: "Wednesday, May 28 - 2025" },
  { first_name: "Matthew", last_name: "Lewis", tags: ["summit"], email: "matthew.lewis@example.com", profile_picture: "https://randomuser.me/api/portraits/men/88.jpg", date: "Friday, Oct 03 - 2025" },
  { first_name: "Harper", last_name: "Walker", tags: [], email: "harper.walker@example.com", profile_picture: null, date: "Monday, Jan 20 - 2025" },
  { first_name: "Joseph", last_name: "Hall", tags: ["team"], email: "joseph.hall@example.com", profile_picture: "https://randomuser.me/api/portraits/men/56.jpg", date: "Thursday, Jun 12 - 2025" },
  { first_name: "Evelyn", last_name: "Allen", tags: ["GITEX DUBAI"], email: "evelyn.allen@example.com", profile_picture: null, date: "Saturday, Mar 14 - 2026" },
  { first_name: "Christopher", last_name: "Young", tags: [], email: "christopher.young@example.com", profile_picture: "https://randomuser.me/api/portraits/men/22.jpg", date: "Tuesday, Jul 22 - 2025" },
  { first_name: "Alexander", last_name: "Martin", tags: ["team"], email: "alexander.martin@example.com", profile_picture: "https://randomuser.me/api/portraits/men/70.jpg", date: "Saturday, Nov 08 - 2025" },
  { first_name: "Abigail", last_name: "King", tags: ["summit", "team"], email: "abigail.king@example.com", profile_picture: null, date: "Thursday, Dec 04 - 2025" },
  { first_name: "Ella", last_name: "Scott", tags: [], email: "ella.scott@example.com", profile_picture: null, date: "Friday, Feb 28 - 2025" },
  { first_name: "Andrew", last_name: "Wright", tags: ["team", "GITEX DUBAI"], email: "andrew.wright@example.com", profile_picture: "https://randomuser.me/api/portraits/men/36.jpg", date: "Monday, Aug 11 - 2025" },
  { first_name: "Joshua", last_name: "Torres", tags: ["GITEX DUBAI"], email: "joshua.torres@example.com", profile_picture: "https://randomuser.me/api/portraits/men/77.jpg", date: "Sunday, Nov 23 - 2025" },
  { first_name: "Elizabeth", last_name: "Nguyen", tags: [], email: "elizabeth.nguyen@example.com", profile_picture: null, date: "Saturday, May 03 - 2025" },
  { first_name: "Ethan", last_name: "Hill", tags: ["summit"], email: "ethan.hill@example.com", profile_picture: "https://randomuser.me/api/portraits/men/91.jpg", date: "Wednesday, Oct 29 - 2025" },
  { first_name: "Sofia", last_name: "Green", tags: ["team"], email: "sofia.green@example.com", profile_picture: null, date: "Sunday, Jan 25 - 2026" },
  { first_name: "Benjamin", last_name: "Adams", tags: [], email: "benjamin.adams@example.com", profile_picture: "https://randomuser.me/api/portraits/men/29.jpg", date: "Friday, Apr 18 - 2025" },
  { first_name: "Avery", last_name: "Baker", tags: ["GITEX DUBAI", "team"], email: "avery.baker@example.com", profile_picture: null, date: "Tuesday, Sep 09 - 2025" },
  { first_name: "Logan", last_name: "Nelson", tags: ["summit"], email: "logan.nelson@example.com", profile_picture: "https://randomuser.me/api/portraits/men/41.jpg", date: "Thursday, Mar 19 - 2026" },
  { first_name: "Ella", last_name: "Carter", tags: [], email: "ella.carter@example.com", profile_picture: null, date: "Saturday, Jun 07 - 2025" },
  { first_name: "Jack", last_name: "Mitchell", tags: ["team"], email: "jack.mitchell@example.com", profile_picture: "https://randomuser.me/api/portraits/men/13.jpg", date: "Monday, Dec 01 - 2025" },
  { first_name: "Scarlett", last_name: "Perez", tags: ["GITEX DUBAI", "summit"], email: "scarlett.perez@example.com", profile_picture: null, date: "Wednesday, Apr 09 - 2025" },
  { first_name: "Samuel", last_name: "Roberts", tags: [], email: "samuel.roberts@example.com", profile_picture: "https://randomuser.me/api/portraits/men/64.jpg", date: "Friday, Jul 25 - 2025" },
  { first_name: "Grace", last_name: "Turner", tags: ["summit"], email: "grace.turner@example.com", profile_picture: null, date: "Sunday, Feb 01 - 2026" },
  { first_name: "Luke", last_name: "Phillips", tags: ["team"], email: "luke.phillips@example.com", profile_picture: "https://randomuser.me/api/portraits/men/9.jpg", date: "Thursday, Nov 20 - 2025" },
  { first_name: "Chloe", last_name: "Campbell", tags: [], email: "chloe.campbell@example.com", profile_picture: null, date: "Saturday, Aug 02 - 2025" },
  { first_name: "Anthony", last_name: "Parker", tags: ["GITEX DUBAI"], email: "anthony.parker@example.com", profile_picture: "https://randomuser.me/api/portraits/men/86.jpg", date: "Monday, Mar 16 - 2026" },
  { first_name: "Dylan", last_name: "Bell", tags: ["GITEX DUBAI", "team"], email: "dylan.bell@example.com", profile_picture: "https://randomuser.me/api/portraits/men/68.jpg", date: "Friday, Nov 14 - 2025" },
  { first_name: "Zoey", last_name: "Evans", tags: ["summit"], email: "zoey.evans@example.com", profile_picture: null, date: "Tuesday, Oct 07 - 2025" },
  { first_name: "Mason", last_name: "Edwards", tags: [], email: "mason.edwards@example.com", profile_picture: "https://randomuser.me/api/portraits/men/94.jpg", date: "Thursday, Jun 19 - 2025" },
  { first_name: "Lily", last_name: "Collins", tags: ["team"], email: "lily.collins@example.com", profile_picture: null, date: "Friday, Feb 13 - 2026" },
  { first_name: "Jacob", last_name: "Stewart", tags: ["summit"], email: "jacob.stewart@example.com", profile_picture: "https://randomuser.me/api/portraits/men/21.jpg", date: "Sunday, Dec 21 - 2025" },
  { first_name: "Hannah", last_name: "Morris", tags: ["team"], email: "hannah.morris@example.com", profile_picture: null, date: "Monday, Jul 14 - 2025" },
  { first_name: "Ryan", last_name: "Rogers", tags: ["GITEX DUBAI", "team"], email: "ryan.rogers@example.com", profile_picture: "https://randomuser.me/api/portraits/men/48.jpg", date: "Wednesday, May 21 - 2025" },
  { first_name: "Victoria", last_name: "Reed", tags: [], email: "victoria.reed@example.com", profile_picture: null, date: "Saturday, Jan 10 - 2026" },
  { first_name: "Noah", last_name: "Cook", tags: ["summit"], email: "noah.cook@example.com", profile_picture: "https://randomuser.me/api/portraits/men/35.jpg", date: "Tuesday, Sep 30 - 2025" },
  { first_name: "Madison", last_name: "Morgan", tags: ["team"], email: "madison.morgan@example.com", profile_picture: null, date: "Thursday, Apr 24 - 2025" },
  { first_name: "Ella", last_name: "Bailey", tags: [], email: "ella.bailey@example.com", profile_picture: null, date: "Sunday, Jun 22 - 2025" }
];
